name: food_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  domain:
    path: ./domain
  navigation:
    path: ./navigation
  home:
    path: ./features/home
  menu:
    path: ./features/menu
  settings:
    path: ./features/settings
  orders:
    path: ./features/orders
  history:
    path: ./features/history
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/