name: food_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  features:
    path: ./features
  profile:
    path: ./future/profile
  navigation:
    path: ./navigation
  data:
    path: ./data
  core:
    path: ./core
  core_ui:
    path: ./core_ui/
  domain:
    path: ./domain

  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  device_info: 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Bold.ttf
        - asset: fonts/poppins/Poppins-Regular.ttf
