name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain

  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.3
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  firebase_storage: ^11.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: