// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4gvGe1T-cRGZUZ371ips08En0efXTTDM',
    appId: '1:1037472218474:web:ce54c2c194523877b27913',
    messagingSenderId: '1037472218474',
    projectId: 'pt-project-4f7ef',
    authDomain: 'pt-project-4f7ef.firebaseapp.com',
    storageBucket: 'pt-project-4f7ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCPGxxFvz1tyJmQh_1EMzk7GsJm6BMF6s',
    appId: '1:1037472218474:android:94bfb401ccaf7854b27913',
    messagingSenderId: '1037472218474',
    projectId: 'pt-project-4f7ef',
    storageBucket: 'pt-project-4f7ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Vn8O834-lQywpVaiOyTfNFnrhOiOw40',
    appId: '1:1037472218474:ios:4830b76885ca0a3ab27913',
    messagingSenderId: '1037472218474',
    projectId: 'pt-project-4f7ef',
    storageBucket: 'pt-project-4f7ef.appspot.com',
    iosClientId: '1037472218474-6na5v4bg60h8bpm3knv51im8q5mq7vk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Vn8O834-lQywpVaiOyTfNFnrhOiOw40',
    appId: '1:1037472218474:ios:4a949d4b80e13c58b27913',
    messagingSenderId: '1037472218474',
    projectId: 'pt-project-4f7ef',
    storageBucket: 'pt-project-4f7ef.appspot.com',
    iosClientId: '1037472218474-ogo1jd4t86gdhfp4al9da85run0a43t7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject.RunnerTests',
  );
}
