name: core_ui
description: Project Core_UI module.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  domain:
    path: ../domain
  menu:
    path: ../features/menu
  orders:
    path: ../features/orders
  navigation:
    path: ../navigation
  authentication:
    path: ../features/authentication
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  readmore: ^2.2.0
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
      - assets/images/
    fonts:
      - family: Poppins
        fonts:
          - asset: ../fonts/poppins/Poppins-Regular.ttf
