name: core_ui
description: Project Core UI module
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
      - assets/images/
    fonts:
      - family: Poppins
        fonts:
          - asset: ../fonts/poppins/Poppins-Regular.ttf
